name: superdeck_workspace

sdkPath: .fvm/flutter_sdk
packages:
  - packages/*
  - demo

command:
  bootstrap:
    environment:
      sdk: ">=3.9.0 <4.0.0"
      flutter: ">=3.35.0"
    dependencies:
      collection: ^1.18.0
      mix: ^2.0.0-dev.4
      ack: ^1.0.0-beta.1
  # publish:
    # hooks:
    #   pre: melos run gen:build

scripts:
  # ANALYSIS
  analyze:
    run: melos run analyze:dart && melos run analyze:dcm
    description: Run standard static analysis checks.
      
  analyze:all:
    run: melos run analyze && melos run analyze:dcm:unused-files && melos run analyze:dcm:unused-code
    description: Run all analysis checks including unused files and code.

  analyze:dart:
    run: melos exec -c 10 -- dart analyze --fatal-infos
    description: Run Dart static analysis checks.

  analyze:dcm:
    run: melos exec -c 10 -- dcm analyze . --fatal-style --fatal-warnings
    description: Run DCM static analysis checks.
    packageFilters:
      dependsOn: "dart_code_metrics_presets"

  analyze:dcm:unused-files:
    run: melos exec -c 10 -- dcm check-unused-files . --fatal-unused
    description: Check for unused files using DCM.
    packageFilters:
      dependsOn: "dart_code_metrics_presets"

  analyze:dcm:unused-code:
    run: melos exec -c 10 -- dcm check-unused-code . --fatal-unused
    description: Check for unused code using DCM.
    packageFilters:
      dependsOn: "dart_code_metrics_presets"

  fix:
    run: melos run fix:dart && melos run fix:dcm
    description: Run all static analysis checks and apply fixes.

  fix:dart:
    run: melos exec -- dart fix --apply .
    description: Run Dart static analysis checks.

  fix:dcm:
    run: melos exec -- dcm fix .
    description: Run DCM static analysis checks.
    packageFilters:
      dependsOn: "dart_code_metrics_presets"

  build_runner:watch:
    run: melos exec --order-dependents -- dart run build_runner watch --delete-conflicting-outputs
    description: Generate code for all packages
    packageFilters:
      dependsOn: "build_runner"

  build_runner:build:
    run: melos run build_runner:clean && melos exec --order-dependents -- dart run build_runner build --delete-conflicting-outputs
    description: Generate code for all packages
    packageFilters:
      dependsOn: "build_runner"

  build_runner:clean:
    run: melos exec --order-dependents -- dart run build_runner clean
    description: Clean generated code for all packages
    packageFilters:
      dependsOn: "build_runner"

  test:
    run: melos exec -- flutter test
    description: Run flutter test
    packageFilters:
      dirExists: test

  test:coverage:
    run: melos exec -- flutter test --coverage
    description: Run flutter test with coverage
    packageFilters:
      dirExists: test

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  brb:
    run: melos run gen:build:superdeck

  brbc:
    run: melos run gen:clean

  custom_lint_analyze:
    run: dart pub global activate custom_lint && melos exec --depends-on="mix_lint" custom_lint
