name: superdeck_example
description: An example presentation for SuperDeck
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  mesh: ^0.4.3
  mix: ^2.0.3
  superdeck_core: ^1.0.0
  superdeck: ^1.0.0
  signals_flutter: ^6.0.4
  naked_ui: ^0.2.0-beta.7
  remix: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  superdeck_cli: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .superdeck/
