targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - lib/**/*.dart
        options:
          skipFields: true
          caseStyle: snakeCase
          enumCaseStyle: snakeCase
          ignoreNull: true
          generateMethods: [decode, encode, stringify, equals]

global_options:
  dart_mappable_builder:
    options:
      caseStyle: snakeCase
      enumCaseStyle: snakeCase
      ignoreNull: true
      generateMethods: [decode, encode, stringify, equals]